name: Build & Publish

on:
  push:
    paths:
      - "src/**"
      - "pyproject.toml"
      - "poetry.lock"

env:
  poetry_version: "1.6.1"

jobs:
  collision-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --user pipx
          pipx install poetry==${{ env.poetry_version }}
          poetry install
      - name: Configure PyPI Configuration
        run: |
          poetry config repositories.pypi https://upload.pypi.org/legacy/
          poetry config pypi-token.pypi ${{ secrets.PYPI_ABSTRACT_METRICS_TOKEN }}
      - name: Attempt Install
        run: |
          pip install abstract-metrics==$(poetry version --short) || exit 0
          echo "Package already exists on PyPI -- run poetry version bump"
          exit 1

  publish:
    runs-on: ubuntu-latest
    needs: [collision-check]
    # Only run if on default branch
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --user pipx
          pipx install poetry==${{ env.poetry_version }}
          poetry install
      - name: Configure Test PyPI Configuration
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_ABSTRACT_METRICS_TOKEN }}
      - name: Configure PyPI Configuration
        run: |
          poetry config repositories.pypi https://upload.pypi.org/legacy/
          poetry config pypi-token.pypi ${{ secrets.PYPI_ABSTRACT_METRICS_TOKEN }}
      - name: Build Package
        run: poetry build
      - name: Publish Test Package
        run: |
          poetry publish \
            --no-interaction \
            --repository test-pypi
      - name: Publish Package
        run: |
          poetry publish \
            --no-interaction \
            --repository pypi
