name: Check All

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --user pipx
          pipx install poetry==1.6.1
          poetry install --with dev
      - name: Format Check
        run: poetry run black --check .
      - name: Lint Python
        run: poetry run ruff .
      - name: Type Check
        run: poetry run pyright src/ tests/
      - name: Test
        run: poetry run pytest .
