name: Check All

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        check:
            - black --check .
            - ruff .
            - pyright src/ tests/
            - pytest . -vv
    env:
      poetry_version: "1.6.1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --user pipx
          pipx install poetry==${{ env.poetry_version }}
          poetry install --with dev
      - name: Poetry Check
        run: poetry check
      - name: Check - ${{ matrix.check }}
        run: |
          poetry run ${{ matrix.check }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
